#!/bin/python
import argparse
from collections import namedtuple
import scipy.io.wavfile as wavf
from ttsvid.audio import quotes_to_audio

Arguments = namedtuple("Arguments", "input output presenter_audio")

def gather_args() -> Arguments:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", help="The quotes to be read by the presenter.", nargs="+", default=[])
    parser.add_argument("--output", help="The file to write the audio to.", default="output.wav")
    parser.add_argument("--presenter-audio", help="The presenter voice to mimic.", required=True)
    args = parser.parse_args()
    return Arguments(
        args.input,
        args.output,
        args.presenter_audio
    )

def generate_quotes(args: Arguments) -> None:
    audio, sample_rate = quotes_to_audio(args.input, args.presenter_audio, pause_seconds=1)
    wavf.write(args.output, sample_rate, audio)

if __name__ == "__main__":
    args = gather_args()
    generate_quotes(args)
